server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: RAGHUL
    password: 6379362346
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate  # Back to validate mode
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    table: flyway_schema_history_customer_service
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: bXlfc3VwZXJfc2VjdXJlX3Rlc3Rfa2V5XzEyMzQ1Njc4OTA=  # Base64 of 32-byte key
  expiration-ms: 3600000

logging:
  level:
    org.flywaydb.core: DEBUG
