CREATE TABLE CUSTOMERS (
    customer_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    dob DATE,
    address VARCHAR2(255) NOT NULL,
    pan VARCHAR2(20) UNIQUE NOT NULL,
    aadhaar VARCHAR2(20) UNIQUE NOT NULL,
    kyc_status VARCHAR2(20) DEFAULT 'PENDING',
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add userId column to CUSTOMERS table
ALTER TABLE CUSTOMERS ADD user_id NUMBER(19) NOT NULL;

-- Add unique constraint
ALTER TABLE CUSTOMERS ADD CONSTRAINT uk_customers_user_id UNIQUE (user_id);

